image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip3 install -r requirements.txt

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: false
    addLabel: prebuilt-in-gitpod